sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.4"
      env: TOXENV=requirements
    - python: "3.5"
      env: TOXENV=lint
    - python: "3.5"
      env: TOXENV=py35
cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox coveralls
language: python
script: tox
after_success: coveralls
